name: Trigger auto deployment for container-app-236xf5enbdgtg

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-236xf5enbdgtg-AutoDeployTrigger-ec160851-b0c2-4dea-ab36-a6a542075b3d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP236XF5ENBDGTG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP236XF5ENBDGTG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP236XF5ENBDGTG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry236xf5enbdgtg.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP236XF5ENBDGTG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP236XF5ENBDGTG_REGISTRY_PASSWORD }}
          containerAppName: container-app-236xf5enbdgtg
          resourceGroup: fototesta118
          imageToBuild: containerregistry236xf5enbdgtg.azurecr.io/container-app-236xf5enbdgtg:${{ github.sha }}
          


